export default [
  { name: "Vue", type: "skill" },
  { name: "React", type: "skill" },
  { name: "AngularJS", type: "skill" },
  { name: "Webpack", type: "skill" },
  { name: "Gulp", type: "skill" },
  { name: "Jest", type: "skill" },
  { name: "Karma", type: "skill" },
  { name: "Jasmine", type: "skill" },
  { name: "Stylus", type: "skill" },
  { name: "Saas", type: "skill" },
  { name: "Less", type: "skill" },
  { name: "PostCSS", type: "skill" },
  { name: "Travis CI", type: "skill" },
  { name: "Circle CI", type: "skill" },
  { name: "Firebase", type: "skill" },
  { name: "Netlify", type: "skill" },
  { name: "AWS S3", type: "skill" },
  { name: "Codecov", type: "skill" },
  { name: "Coveralls", type: "skill" },
  { name: "HTTP", type: "skill" },
  { name: "REST", type: "skill" },
  { name: "Node", type: "skill" },
  { name: "Express", type: "skill" },
  { name: "MongoDB", type: "skill" },
  { name: "Ruby on Rails", type: "skill" },
  { name: "Postgres", type: "skill" },
  { name: "Docker", type: "skill" },
  { name: "Glorious Codes", type: "experience" },
  { name: "RD Station", type: "experience" },
  { name: "Bcredi", type: "experience" },
  { name: "Conta Azul", type: "experience" },
  { name: "JobScore", type: "experience" },
  { name: "Glorious Demo", type: "project" },
  { name: "Pitsby", type: "project" },
  { name: "Nashios", type: "project" },
  { name: "Woblast", type: "project" },
  { name: "Weather Now", type: "project" },
  { name: "Teleflik", type: "project" }
];
